def build_cleaning_payload(
    drop_empty_rows_option: bool,
    remove_repeated_header_rows_option: bool,
    repeated_header_column,
    repeated_header_value,
    cast_numeric_option: bool,
    numeric_columns: list[str],
    cast_datetime_option: bool,
    datetime_column,
    datetime_format,
    drop_na_option: bool,
    drop_na_subset: list[str],
    drop_duplicates_option: bool,
    duplicate_subset: list[str],
    drop_columns_option: bool,
    columns_to_drop: list[str],
    missing_strategy: str,
    missing_group_column: str,
    add_missing_flags: bool,
) -> dict:
    return {
        "drop_empty_rows": drop_empty_rows_option,
        "remove_repeated_header_rows": remove_repeated_header_rows_option,
        "repeated_header_column": repeated_header_column,
        "repeated_header_value": repeated_header_value,
        "cast_numeric": cast_numeric_option,
        "numeric_columns": numeric_columns,
        "cast_datetime": cast_datetime_option,
        "datetime_column": datetime_column,
        "datetime_format": datetime_format if datetime_format else None,
        "drop_na": drop_na_option,
        "drop_na_subset": drop_na_subset,
        "drop_duplicates": drop_duplicates_option,
        "duplicate_subset": duplicate_subset,
        "drop_columns": drop_columns_option,
        "columns_to_drop": columns_to_drop,
        "missing_strategy": missing_strategy,
        "missing_group_column": missing_group_column,
        "add_missing_flags": add_missing_flags,
    }